-- Create NOTIFICATION table if it doesn't exist
CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NOTIFICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    MESSAGE VARCHAR(255) NOT NULL,
    CLAIM_ID INT,
    IS_READ BOOLEAN DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CLAIM_ID) REFERENCES CLAIM(CLAIM_ID) ON DELETE CASCADE
);

-- Create index for faster queries
CREATE INDEX idx_user_notifications ON NOTIFICATION(USER_ID, IS_READ);
CREATE INDEX idx_created_at ON NOTIFICATION(CREATED_AT);
